### ISSUE TITLE
Residue number and name

### ISSUE THREAD

**Issue by diallobakary4** [UnixJunkie/arpeggio#1]
Hello there :)

Is it possible to also have the residue name in the arpeggio output.
For now there is: Chain/residue number/atom.
It can be more convenient for analysis to have Chain/residue number/residue name/atom.

**Comment by UnixJunkie** [comment]
Please report your issue there:
https://bitbucket.org/harryjubb/arpeggio
Here is only a mirror repository. I am not one of the authors of arpeggio neither affiliated with them.

**Comment by UnixJunkie** [comment]
you might be interested in PLIP also (open source and on github)
